export default [{
    view: '@./weather/index',
    dockX: 10,
    dockY: 93,
    width: 172,
    height: 24,
    dockXKey: 'right',
    dockYKey: 'bottom'
}, {
    view: '@./bg/index',
    dockX: 14,
    dockY: 10,
    width: 310,
    height: 70,
    dockXKey: 'right',
    dockYKey: 'bottom'
}, {
    view: '@./mplayer/index',
    dockX: 10,
    dockY: 20,
    dockXKey: 'right',
    dockYKey: 'top',
    width: 610,
    height: 30
}, {
    view: '@./lunar/index',
    dockX: 300,
    dockY: 10,
    width: 350,
    height: 250,
    dockXKey: 'left',
    dockYKey: 'top'
}];