export default [{
    view: '@mx:./weather/index',
    dockX: 10,
    dockY: 93,
    width: 172,
    height: 24,
    dockXKey: 'right',
    dockYKey: 'bottom'
}, {
    view: '@mx:./bg/index',
    dockX: 14,
    dockY: 10,
    width: 310,
    height: 70,
    dockXKey: 'right',
    dockYKey: 'bottom'
}, {
    view: '@mx:./mplayer/index',
    dockX: 10,
    dockY: 20,
    dockXKey: 'right',
    dockYKey: 'top',
    width: 610,
    height: 30
}, {
    view: '@mx:./lunar/index',
    dockX: 300,
    dockY: 50,
    width: 350,
    height: 200,
    dockXKey: 'left',
    dockYKey: 'top'
}, {
    view: '@mx:./clock/index',
    dockX: 10,
    dockY: 283,
    width: 150,
    height: 150,
    dockXKey: 'right',
    dockYKey: 'bottom'
}];